apiVersion: v1
kind: Service
metadata:
  name: {{ template "name" . }}
spec:
  type: ClusterIP
  selector:
    app: core-frontend
  ports:
    - protocol: TCP
      port: {{ .Values.app.port }}
      targetPort: {{ .Values.app.port }}
