apiVersion: v1
kind: Service
metadata:
  name: {{ template "name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: core-backend
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.app.port }}
